services:
  - type: web
    name: vinylzz-web
    env: node
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DISCOGS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_SSL
        value: "true"
      # ✅ uploads live in ephemeral /tmp on Free
      - key: UPLOAD_DIR
        value: /tmp/uploads

  - type: worker
    name: vinylzz-worker
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci
    startCommand: node worker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DISCOGS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_SSL
        value: "true"

